name: SonarCloud Analysis

on:
  push:
    branches:
      - main  # Adjust as needed
  pull_request:
    branches:
      - main  # Adjust as needed

jobs:
  build:
    runs-on: ubuntu-latest  # or windows-latest if you're using Windows

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: '7.0'

    - name: List files (check file paths)
      run: ls -R

    - name: Install SonarScanner
      run: |
        dotnet tool install --global dotnet-sonarscanner

    - name: Remove BOM from .sln file
      run: |
        echo "Removing BOM from .sln file"
        sed -i '1s/^\xEF\xBB\xBF//' /home/runner/work/StudentManagementSystem/StudentManagementSystem/StudentManagementSystem.sln

    - name: Verify BOM removal and file contents
      run: |
        echo "Verifying contents of StudentManagementSystem.sln"
        ls -l /home/runner/work/StudentManagementSystem/StudentManagementSystem/StudentManagementSystem.sln
        cat /home/runner/work/StudentManagementSystem/StudentManagementSystem/StudentManagementSystem.sln

    - name: Restore dependencies
      run: dotnet restore StudentManagementSystem.sln

    - name: Clean Solution
      run: dotnet clean StudentManagementSystem.sln

    - name: Build Solution
      run: dotnet build StudentManagementSystem.sln --configuration Release

    - name: Run SonarScanner Begin
      run: |
        echo "Running SonarScanner in directory: $(pwd)"
        dotnet sonarscanner begin /k:"Kavana179_StudentManagementSystem" /o:"kavana179" /d:sonar.login="${{ secrets.SONAR_TOKEN }}" /s:"StudentManagementSystem.sln" /d:sonar.verbose=true

    - name: Run Tests
      run: |
        dotnet test StudentManagementSystem.sln --configuration Release --no-build --logger "trx;LogFileName=test-results.trx"

    - name: Run SonarScanner End
      run: |
        dotnet sonarscanner end /d:sonar.login="${{ secrets.SONAR_TOKEN }}"
